### ISSUE TITLE
size cannot be greater than 1024

### ISSUE THREAD

**Issue by Pashy83** [kyan001/ping3#40]
When calling ping and specifying size it returns an error if over 1024 bytes.  Looking at the ping3 code comments suggest maximum should be around 1450.  

This was done on Windows 7 64 Bit SP1 Python 3.8

```
Traceback (most recent call last):
  File "WindBackTest.py", line 203, in <module>
    test_network(semIPAddress, None)
  File "WindBackTest.py", line 143, in test_network
    pingReturn = ping(semip, timeout=3, size=1440, unit='ms')
  File "C:\Users\Controls\AppData\Local\Programs\Python\Python38\lib\site-packag
es\ping3.py", line 83, in wrapper
    func_return = func(*args, **kwargs)
  File "C:\Users\Controls\AppData\Local\Programs\Python\Python38\lib\site-packag
es\ping3.py", line 304, in ping
    delay = receive_one_ping(sock=sock, icmp_id=icmp_id, seq=seq, timeout=timeou
t)  # in seconds
  File "C:\Users\Controls\AppData\Local\Programs\Python\Python38\lib\site-packag
es\ping3.py", line 83, in wrapper
    func_return = func(*args, **kwargs)
  File "C:\Users\Controls\AppData\Local\Programs\Python\Python38\lib\site-packag
es\ping3.py", line 220, in receive_one_ping
    recv_data, addr = sock.recvfrom(1024)
OSError: [WinError 10040] A message sent on a datagram socket was larger than th
e internal message buffer or some other network limit, or the buffer used to rec
eive a datagram into was smaller than the datagram itself
```

Line 220 has recvfrom set to expect 1024.  There might be others

**Comment by Pashy83** [comment]
Sorry 996 is max.  1024 -20 -8

**Comment by kyan001** [comment]
Hi @Pashy83 ,

Thank you for the feedback. In version 2.9.3, the buffer size is adjusted to 1500 bytes. This should be enough in most cases. If you think of a different number, please tell me anytime.
