### ISSUE TITLE
Destination unreachible causes AttributeError in DestinationUnreachible

### ISSUE THREAD

**Issue by drisen** [kyan001/ping3#52]
In Windows 10, Python 3.8, ping version 4.0.0, using WiFi access to the network: if the laptop's WiFi disconnects, ping3.ping detects that the destination is unreachable, but then dies processing the error with an AttributeError in class DestinationUnreachable. E.g.

Traceback (most recent call last):
  File "G:/My Drive/Case/PyCharm/netstats/ping_stats.py", line 47, in <module>
    result = ping3.ping(site.ipAddress, timeout=timeout, unit='ms', size=56)
  File "C:\Users\dar5\AppData\Local\Programs\Python\Python38\lib\site-packages\ping3\__init__.py", line 83, in wrapper
    func_return = func(*args, **kwargs)
  File "C:\Users\dar5\AppData\Local\Programs\Python\Python38\lib\site-packages\ping3\__init__.py", line 311, in ping
    delay = receive_one_ping(sock=sock, icmp_id=icmp_id, seq=seq, timeout=timeout)  # in seconds
  File "C:\Users\dar5\AppData\Local\Programs\Python\Python38\lib\site-packages\ping3\__init__.py", line 83, in wrapper
    func_return = func(*args, **kwargs)
  File "C:\Users\dar5\AppData\Local\Programs\Python\Python38\lib\site-packages\ping3\__init__.py", line 240, in receive_one_ping
    raise errors.DestinationHostUnreachable(ip_header=ip_header, icmp_header=icmp_header)
  File "C:\Users\dar5\AppData\Local\Programs\Python\Python38\lib\site-packages\ping3\errors.py", line 30, in __init__
    super().__init__(self.message)
  File "C:\Users\dar5\AppData\Local\Programs\Python\Python38\lib\site-packages\ping3\errors.py", line 21, in __init__
    self.message = message if self.ip_header is None else message + " (Host='{}')".format(self.ip_header.get("src_addr"))
AttributeError: 'str' object has no attribute 'get'

**Comment by kyan001** [comment]
Hi @drisen ,

Sorry for the inconvenience. I'll look into the bug. Is it possible to have the debug outputs for such a case? Just turn on `ping3.DEBUG = True` right after `import ping3`. It would be a great help to address the problem.

Thanks.

**Comment by canepan** [comment]
Hi, I noticed the same under Linux.
No output change even with `ping3.DEBUG = True`:
```
Traceback (most recent call last):
  File "/etc/keepalived/bin/status.py", line 501, in <module>
    sys.exit(main())
  File "/etc/keepalived/bin/status.py", line 482, in main
    if rstatus.reachable:
  File "/etc/keepalived/bin/status.py", line 307, in reachable
    if failback_ping(self.rhost, port=22):
  File "/etc/keepalived/bin/net_utils.py", line 16, in failback_ping
    return ping(*args, **kwargs)
  File "/mnt/opt/nicola/tools/lib/python3.7/site-packages/ping3/__init__.py", line 83, in wrapper
    func_return = func(*args, **kwargs)
  File "/mnt/opt/nicola/tools/lib/python3.7/site-packages/ping3/__init__.py", line 311, in ping
    delay = receive_one_ping(sock=sock, icmp_id=icmp_id, seq=seq, timeout=timeout)  # in seconds
  File "/mnt/opt/nicola/tools/lib/python3.7/site-packages/ping3/__init__.py", line 83, in wrapper
    func_return = func(*args, **kwargs)
  File "/mnt/opt/nicola/tools/lib/python3.7/site-packages/ping3/__init__.py", line 240, in receive_one_ping
    raise errors.DestinationHostUnreachable(ip_header=ip_header, icmp_header=icmp_header)
  File "/mnt/opt/nicola/tools/lib/python3.7/site-packages/ping3/errors.py", line 30, in __init__
    super().__init__(self.message)
  File "/mnt/opt/nicola/tools/lib/python3.7/site-packages/ping3/errors.py", line 21, in __init__
    self.message = message if self.ip_header is None else message + " (Host='{}')".format(self.ip_header.get("src_addr"))
AttributeError: 'str' object has no attribute 'get'
```

**Comment by canepan** [comment]
I think it can be resolved by changing line 30 (and possibly the same lines doing the same) with:
```
    super().__init__(message=self.message)
```
